In [1]:
# Visualizing Netflix Content Analytics
# Data Wrangling

In [2]:
# Import all the required libraries
import pandas as pd
import numpy as np
import pandas_profiling as pp
import re

In [3]:
# Read the CSV file into a new dataframe "df_content"
df_content = pd.read_csv("E:\PG - MS BA\Personal Projects\Visualizing Netflix Content Analytics\\Netflix Data.csv")

In [4]:
# Print "df_content"
df_content

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...
...,...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
6230,70286564,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,NaN,2016,NaN,60 min,Movies,Nursery rhymes and original music for children...
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ..."
6233,70153404,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...

In [5]:
# Profile the dataset "Netflix Data.csv" to generate initial report
from pandas_profiling import ProfileReport
file = pd.read_csv("E:\PG - MS BA\Personal Projects\Visualizing Netflix Content Analytics\\Netflix Data.csv")
profile = ProfileReport(file, title = "Profile")
profile.to_file("Netflix Profile Report Initial.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [6]:
# Print the number of rows and columns in "df_content"
df_content.shape

(6234, 12)

In [7]:
# Print the description of "df_content"
df_content.describe

<bound method NDFrame.describe of        show_id     type                                        title  \
0     81145628    Movie      Norm of the North: King Sized Adventure
1     80117401    Movie                   Jandino: Whatever it Takes
2     70234439  TV Show                           Transformers Prime
3     80058654  TV Show             Transformers: Robots in Disguise
4     80125979    Movie                                 #realityhigh
...        ...      ...                                          ...
6229  80000063  TV Show                                 Red vs. Blue
6230  70286564  TV Show                                        Maron
6231  80116008    Movie       Little Baby Bum: Nursery Rhyme Friends
6232  70281022  TV Show  A Young Doctor's Notebook and Other Stories
6233  70153404  TV Show                                      Friends

                      director  \
0     Richard Finn, Tim Maltby
1                          NaN
2                          NaN
3                          NaN
4             Fernando Lebrija
...                        ...
6229                       NaN
6230                       NaN
6231                       NaN
6232                       NaN
6233                       NaN

                                                   cast  \
0     Alan Marriott, Andrew Toth, Brian Dobson, Cole...
1                                      Jandino Asporaat
2     Peter Cullen, Sumalee Montano, Frank Welker, J...
3     Will Friedle, Darren Criss, Constance Zimmer, ...
4     Nesta Cooper, Kate Walsh, John Michael Higgins...
...                                                 ...
6229  Burnie Burns, Jason Saldaña, Gustavo Sorola, G...
6230  Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...
6231                                                NaN
6232  Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...
6233  Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...

                                       country         date_added  \
0     United States, India, South Korea, China  September 9, 2019
1                               United Kingdom  September 9, 2016
2                                United States  September 8, 2018
3                                United States  September 8, 2018
4                                United States  September 8, 2017
...                                        ...                ...
6229                             United States                NaN
6230                             United States                NaN
6231                                       NaN                NaN
6232                            United Kingdom                NaN
6233                             United States                NaN

      release_year    rating    duration  \
0             2019     TV-PG      90 min
1             2016     TV-MA      94 min
2             2013  TV-Y7-FV    1 Season
3             2016     TV-Y7    1 Season
4             2017     TV-14      99 min
...            ...       ...         ...
6229          2015        NR  13 Seasons
6230          2016     TV-MA   4 Seasons
6231          2016       NaN      60 min
6232          2013     TV-MA   2 Seasons
6233          2003     TV-14  10 Seasons

                                              listed_in  \
0                    Children & Family Movies, Comedies
1                                       Stand-Up Comedy
2                                              Kids' TV
3                                              Kids' TV
4                                              Comedies
...                                                 ...
6229  TV Action & Adventure, TV Comedies, TV Sci-Fi ...
6230                                        TV Comedies
6231                                             Movies
6232           British TV Shows, TV Comedies, TV Dramas
6233                     Classic & Cult TV, TV Comedies

                                            description
0     Before planning an awesome wedding for his gra...
1     Jandino Asporaat riffs on the challenges of ra...
2     With the help of three human allies, the Autob...
3     When a prison ship crash unleashes hundreds of...
4     When nerdy high schooler Dani finally attracts...
...                                                 ...
6229  This parody of first-person shooter games, mil...
6230  Marc Maron stars as Marc Maron, who interviews...
6231  Nursery rhymes and original music for children...
6232  Set during the Russian Revolution, this comic ...
6233  This hit sitcom follows the merry misadventure...

[6234 rows x 12 columns]>

In [8]:
# Print the unique values for each column in "df_content"
for c in df_content.columns:
    n = df_content[c].unique()
    # If the number of unique values is less than 30, print the values. Otherwise, print the number of unique values
    if len(n) < 30:
        print(c)
        print(n)
    else:
        print(c + " : " + str(len(n)) + " unique values")

show_id : 6234 unique values
type
['Movie' 'TV Show']
title : 6172 unique values
director : 3302 unique values
cast : 5470 unique values
country : 555 unique values
date_added : 1525 unique values
release_year : 72 unique values
rating
['TV-PG' 'TV-MA' 'TV-Y7-FV' 'TV-Y7' 'TV-14' 'R' 'TV-Y' 'NR' 'PG-13' 'TV-G'
 'PG' 'G' nan 'UR' 'NC-17']
duration : 201 unique values
listed_in : 461 unique values
description : 6226 unique values

In [9]:
# Find the columns with missing values in "df_content"
print("The columns with missing values are as follows:")
for c in df_content.columns:
    m = df_content[c].isnull().sum()
    if m > 0:
        print("{} : {} missing value(s)".format(c,m))

The columns with missing values are as follows:
director : 1969 missing value(s)
cast : 570 missing value(s)
country : 476 missing value(s)
date_added : 11 missing value(s)
rating : 10 missing value(s)

In [10]:
# Handle the columns with missing values in "df_content"
df_content["director"] = df_content["director"].fillna("Unknown")
df_content["cast"] = df_content["cast"].fillna("Unknown")
df_content["country"] = df_content["country"].fillna("Unknown")
df_content["date_added"] = df_content["date_added"].fillna("Unknown")
df_content["rating"] = df_content["rating"].fillna("Unknown")
df_content

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,Unknown,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,Unknown,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,Unknown,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...
...,...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,TV Show,Red vs. Blue,Unknown,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,Unknown,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
6230,70286564,TV Show,Maron,Unknown,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,Unknown,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,Unknown,Unknown,Unknown,Unknown,2016,Unknown,60 min,Movies,Nursery rhymes and original music for children...
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,Unknown,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,Unknown,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ..."
6233,70153404,TV Show,Friends,Unknown,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,Unknown,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...

In [11]:
# Rename the columns in "df_content"
df_content.rename(columns = {"show_id":"ID", "type":"Type", "title":"Title", "director":"Director", "cast":"Cast", "country":"Country", "date_added":"Date Added", "release_year":"Release Year", "rating":"Rating", "duration":"Duration", "listed_in":"Listed In", "description":"Description"}, inplace = True)
df_content

,ID,Type,Title,Director,Cast,Country,Date Added,Release Year,Rating,Duration,Listed In,Description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,Unknown,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,Unknown,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,Unknown,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...
...,...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,TV Show,Red vs. Blue,Unknown,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,Unknown,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
6230,70286564,TV Show,Maron,Unknown,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,Unknown,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,Unknown,Unknown,Unknown,Unknown,2016,Unknown,60 min,Movies,Nursery rhymes and original music for children...
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,Unknown,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,Unknown,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ..."
6233,70153404,TV Show,Friends,Unknown,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,Unknown,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...

In [12]:
# Rearrange the columns in "df_content"
df_content = df_content[["ID", "Type", "Title", "Director", "Cast", "Country", "Duration", "Rating", "Release Year", "Date Added", "Listed In", "Description"]]
df_content

,ID,Type,Title,Director,Cast,Country,Duration,Rating,Release Year,Date Added,Listed In,Description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",90 min,TV-PG,2019,"September 9, 2019","Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,Unknown,Jandino Asporaat,United Kingdom,94 min,TV-MA,2016,"September 9, 2016",Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,Unknown,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,1 Season,TV-Y7-FV,2013,"September 8, 2018",Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,Unknown,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,1 Season,TV-Y7,2016,"September 8, 2018",Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,99 min,TV-14,2017,"September 8, 2017",Comedies,When nerdy high schooler Dani finally attracts...
...,...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,TV Show,Red vs. Blue,Unknown,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,13 Seasons,NR,2015,Unknown,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
6230,70286564,TV Show,Maron,Unknown,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,4 Seasons,TV-MA,2016,Unknown,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,Unknown,Unknown,Unknown,60 min,Unknown,2016,Unknown,Movies,Nursery rhymes and original music for children...
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,Unknown,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,2 Seasons,TV-MA,2013,Unknown,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ..."
6233,70153404,TV Show,Friends,Unknown,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,10 Seasons,TV-14,2003,Unknown,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...

In [13]:
# Profile the final dataframe "df_content" to generate final report
from pandas_profiling import ProfileReport
profile = ProfileReport(df_content, title = "Profile")
profile.to_file("Netflix Profile Report Final.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [14]:
# Write the dateframe "df_content" to a Microsoft Excel file
df_content.to_excel("E:\PG - MS BA\Personal Projects\Visualizing Netflix Content Analytics\\Netflix Data (Final).xlsx", sheet_name = "Netflix Data", index = False)